[package]
name = "zipunsplit"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["derive"] }
zipunsplitlib = { path = "../zipunsplitlib" }
